spring:
  profiles:
    active: prod
  thymeleaf:
    mode: LEGACYHTML5
  devtools:
    restart:
      additional-paths: src/main/kotlin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    location: C:\Users\MSI-PC\.m2\repository\mysql\mysql-connector-java\5.1.43\mysql-connector-java-5.1.43
    url: jdbc:mysql://localhost:3306
    username: ly
    password: ly19955125
testaaa:
  aaa: sgoyi
server:
  port: 8881